# Generated by Django 6.0.5 on 2026-05-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_rename_room_bookings_room_number_alter_bookings_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='privilages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilage_name', models.CharField(max_length=50)),
                ('privilage_desc', models.CharField(max_length=1000)),
                ('tier_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='redemption_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=500)),
                ('points_required', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='membership_plans',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='membership_plans',
            name='duration_months',
        ),
    ]
