# Generated by Django 6.0.5 on 2026-05-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_privilages_redemption_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership_plans',
            name='tier_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='privilages',
            name='tier_level',
            field=models.IntegerField(default=1),
        ),
    ]
