# Generated by Django 6.0.5 on 2026-05-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tier_level',
            field=models.IntegerField(default=1),
        ),
    ]
